### ISSUE TITLE
data problem

### ISSUE THREAD

**Issue by futianfan** [DirectMolecularConfGen/DMCG#1]
hi i run the code following your instruction and got the following bugs. do you know how to fix it? 

Traceback (most recent call last):
  File "train.py", line 359, in <module>
    main()
  File "train.py", line 190, in main
    remove_hs=args.remove_hs,
  File "/net/sunlab/psunlab1/molecular_data/graphnn/DMCG/confgen/e2c/dataset.py", line 61, in __init__
    super().__init__(self.folder, transform, pre_transform)
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 88, in __init__
    self._process()
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 171, in _process
    self.process()
  File "/net/sunlab/psunlab1/molecular_data/graphnn/DMCG/confgen/e2c/dataset.py", line 87, in process
    self.process_confgf()
  File "/net/sunlab/psunlab1/molecular_data/graphnn/DMCG/confgen/e2c/dataset.py", line 336, in process_confgf
    data, slices = self.collate(data_list)
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 116, in collate
    add_batch=False,
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 86, in collate
    increment)
  File "/nethome/tfu42/.conda/envs/dmcg2/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 128, in _collate
    cat_dim = data_list[0].__cat_dim__(key, elem, stores[0])
TypeError: __cat_dim__() takes 3 positional arguments but 4 were given

**Comment by DirectMolecularConfGen** [comment]
I think this error is caused by torch_geometric version. We use `torch_geometric == 1.7.2` in our code. Can you check the version you used in you conda env?

**Comment by futianfan** [comment]
thanks, what is your pytorch version?

**Comment by futianfan** [comment]
it works now. thanks!

**Comment by rewquiofds** [comment]
> it works now. thanks!

Hi, how did you solve it? By lowering the PyG version? Thanks

**Comment by hengck23** [comment]
the solution is found in https://github.com/pyg-team/pytorch_geometric/issues/4358

modify e2c/dataset.py

```

class CustomData(Data):
    def __cat_dim__(self, key, value,):

class CustomData(Data):
    def __cat_dim__(self, key, value, *args, **kwargs):

```
